### PR TITLE
Improve slicer integration

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@cpinter  For this PR, I suggest we do not add the layout node. Since the vr view node parent layout is set to be itself, I think it is needed.

**Comment by jcfr** [comment]
Also [r26891](http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=26891) fixes the module name extraction issue, it means there is no need to rename it.

**Comment by cpinter** [comment]
> I suggest we do not add the layout node. Since the vr view node parent layout is set to be itself, I think it is needed

Agreed, it's not needed. I didn't exclude it because we'll need one anyway, and creating the placeholder is also work.

**Comment by cpinter** [comment]
> no need to rename it

Well you have to decide there. Any strong preference for VR?

**Comment by jcfr** [comment]
> I didn't exclude it because we'll need one anyway, and creating the placeholder is also useful.

👍  

> Any strong preference for "VR"

True that `vr` also means volume rendering

**Pull request merged**
